# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29b259404cf3cb0cff43b82dfeea868146bc6bda0963d49531e6a41e384af8e630769dcbe604c059b746891fd63da74bdcdbda032c6c1d14a994ef30a5a9ae53

test:
  secret_key_base: 2584d6d0c3001fef77c1a8bf451277362cd6c41abc55e864d0d9c85a66df40e888d29c441d17e9fbae0f3ad3e131468d5b1d3c57174b8b1cd12f2012c7c36b5d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
