# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a2b1c650a40cb5c46af9eaf61758f35b4d58e672c75536e4ea6f3e525b67d8ed93bb67ad0587c45a0748ff18c855d4da1b330b66e261deb61067a892d0abb4c

test:
  secret_key_base: c767e332d6838a7d84a114767f0e2e16ff1576dc39e9bab3541b3f47bc9d42b64eb5b97bb781e1c277d2745ac45b67469841f80936c6679b7433c26c7203563d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
